//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_detail
    {
        public int id_bill_detail { get; set; }
        public string bill_id { get; set; }
        public string product_id { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
