//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public string id_bill { get; set; }
        public string user_id { get; set; }
        public string status_id { get; set; }
        public Nullable<int> total { get; set; }
        public string description { get; set; }
    }
}
