//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public string id_branch { get; set; }
        public string name_branch { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public string description { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
