//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string id_product { get; set; }
        public string name_product { get; set; }
        public string description { get; set; }
        public int price { get; set; }
        public Nullable<int> sale { get; set; }
        public Nullable<long> date_create { get; set; }
        public string branch_id { get; set; }
        public string status_id { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> quantity { get; set; }
        public string image { get; set; }
    }
}
