//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_category
    {
        public string id_sub_category { get; set; }
        public string name_sub_category { get; set; }
        public string category_id { get; set; }
        public string description { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
